.TH MKTMPFS 1 "21 July 2019"
.SH NAME
mktmpfs \- create temporary file system on top of a encrypted volume
.
.SH SYNOPSIS
.SY mktmpfs
.OP \-dr
.OP \-f fs
.OP \-c cipher
.OP \-m mode
.OP \-o owner
.I dev mnt name
.YS
.
.SH DESCRIPTION
.B mktmpfs
is a tool for quickly creating mount points for temporary files.
Unlike tmpfs,
.B mktmpfs
does not store files in memory.
Instead, an encrypted volume is set up with
.BR cryptset (8)
and a random key.
.
.SH OPTIONS
.TP
.BR \-d , " \-\-discard"
Discard device
.I dev
before formatting with
.BR blkdiscard (8).
See the
.B discard
option in
.BR mount (8)
for details on why this might be useful.
This flag also mounts the filesystem with the
.BR mount (8)
option
.BR discard .
.IP
.IR Note :
This can leak details of the usage of the encrypted filesystem.
.
.TP
.BR \-r , " \-\-remove"
Remove device instead of adding.
.
.TP
.BR \-f , " \-\-fs "\c
.I fs
Format filesystem with
.IR fs .
See
.BR mkfs (8)
for details.
.
.TP
.BR \-c , " \-\-cipher "\c
.I cipher
Use
.I cipher
for encryption.
See the Device Mapper documentation on the
.B crypt
target for what is permitted.
.
.TP
.BR \-m , " \-\-mode "\c
.I mode
The file mode bits that the filesystem should be mounted with.
See
.BR chmod (1)
for details.
.
.TP
.BR \-o , " \-\-owner "\c
.I owner
The owner of the filesystem.
See
.BR chown (1)
for details.
.
.SH ENVIRONMENT
.B mktmpfs
supports all of the above options (with the exception of
.BR \-\-remove )
as environment variables.
The environment variables are simply the uppercase versions of the long option
names (i.e. to set
.BR \-\-discard ,
.I DISCARD=yes
is used.)
.IR "DEV MNT " and " NAME
are used to denote the device path, mount point and devicemapper-nam respectively.
.
.SH EXIT STATUS
.TP
.B 0
Successful operation.
.TP
.B 1
Incorrect usage/bad parameters.
.
.TP
.B 2
Failure to carry out operation.
.
.SH AUTHOR
.MT torin@tcarey.uk
Torin Carey
.ME
.
.SH SEE ALSO
.BR cryptsetup (8),
.BR blkdiscard (8),
.BR mkfs (8)
